### ISSUE TITLE
Bei Trainingsmodus endlich, beim letzten Block auch nach_intervall_pause auf True setzen

### ISSUE THREAD

**Issue by doku2525** [doku2525/ErgoInoTrainer#27]
**Beschreibung** Bei endlichem Training kann man nicht erkennen, ob nach dem aktuellen Block das Training abgeschlossen ist. Deshalb sollte beim letzten Block das nach_inhalt_pause-Zeichen zu sehen sein. Wenn man dann die Pause aufhebt, werden auch BEIDE Variablen auf False gesetzt.
**Labels** backend, frontend
**Meilenstein** Version 0.1

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the ViewDatenmodell class to include logic for showing the pause symbol (⊗) for the last block of a finite training program. Updated the update_daten_modell method to set this flag.

You can review changes in this commit: https://github.com/mnmnk43434/doku2525-ErgoInoTrainer-27/commit/77b31a25c42263b182d66c67cff137819b1e5e2c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
